/**
 * F126 - Branch Protection Rule Auto-Suggester.
 *
 * Companion to F71 force-push guard + F119 overview picker. For a
 * branch that's unprotected / guarded / unknown, suggest a starter
 * ruleset and (with confirmation) PUT it via gh api.
 *
 * Flow:
 *   1. Resolve the branch + repo + current protection (probes via gh).
 *   2. Classify the branch role (default / release / hotfix / long-lived /
 *      feature / other).
 *   3. Probe environment signals (CI workflows, CODEOWNERS, signed
 *      commits in recent history).
 *   4. Call suggestProtectionRules + open the markdown preview.
 *   5. Multi-select picker of suggestions. Default-picked are the
 *      `recommended` tier.
 *   6. Modal confirm + PUT via `gh api -X PUT
 *      repos/:o/:r/branches/:b/protection -F input=@-` with the JSON body
 *      generated by buildProtectionPutBody.
 *
 * The "Open settings page" alternate action lets the user wire it up
 * by hand in the GitHub UI if they prefer that surface.
 *
 * Hard requirements: gh CLI on PATH, GitHub origin.
 */
import * as vscode from 'vscode';
import { execFile } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs/promises';
import * as path from 'path';
import { Git } from '../git/git';
import { RepoManager } from '../git/repoManager';
import { parseGitHubRepo, classifyProtection, ProtectionDecision } from '../git/forcePushGuard';
import {
  classifyBranchRole,
  suggestProtectionRules,
  buildProtectionPutBody,
  buildSuggestionPreview,
  describeSuggestionVerdict,
  BranchRole,
  RuleSuggestion,
  EnvironmentSignals,
} from '../git/branchProtectionSuggest';
import {
  computeProtectionDelta,
  classifyDeltaVerdict,
  selectDeltaRows,
  describeDeltaRow,
  describeDeltaTitle,
  buildDeltaReport,
  pickAllChanges,
  ProtectionRuleDelta,
} from '../git/branchProtectionSuggestDelta';

const pexec = promisify(execFile);

export async function suggestBranchProtection(repos: RepoManager, branchHint?: string): Promise<void> {
  const git = repos.primary();
  if (!git) {
    vscode.window.showWarningMessage('GitSight: no git repo in workspace.');
    return;
  }
  if (!(await ghAvailable())) {
    vscode.window.showWarningMessage('GitSight: gh CLI not found - cannot probe or set branch protection.');
    return;
  }
  const repo = await resolveGitHubRepo(git);
  if (!repo) {
    vscode.window.showInformationMessage('GitSight: origin is not a GitHub remote.');
    return;
  }
  const branch = await resolveBranch(git, branchHint);
  if (!branch) {
    vscode.window.showInformationMessage('GitSight: no branch selected (detached HEAD?).');
    return;
  }

  const result = await vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: `GitSight: analysing protection for \`${branch}\`\u2026`,
    },
    async () => {
      const [decision, defaultBranch, signals] = await Promise.all([
        probeBranch(repo.owner, repo.repo, branch),
        loadDefaultBranch(git),
        loadEnvironmentSignals(git),
      ]);
      const role = classifyBranchRole({ branch, defaultBranch });
      const suggestions = suggestProtectionRules({ branch, role, current: decision, signals });
      return { decision, defaultBranch, signals, role, suggestions };
    },
  );

  if (result.suggestions.length === 0) {
    vscode.window.showInformationMessage(
      `GitSight: \`${branch}\` (${result.role}) already covers the recommended baseline.`,
    );
    return;
  }

  // Show the preview first so the user can read the rationale before
  // touching the multi-select.
  const previewMd = buildSuggestionPreview({
    branch, role: result.role, suggestions: result.suggestions, signals: result.signals,
  });
  const action = await vscode.window.showInformationMessage(
    describeSuggestionVerdict({ branch, suggestions: result.suggestions }),
    'Open preview', 'Pick rules to apply', 'Open settings page',
  );
  if (!action) return;
  if (action === 'Open settings page') {
    await vscode.env.openExternal(vscode.Uri.parse(
      `https://github.com/${repo.owner}/${repo.repo}/settings/branches`,
    ));
    return;
  }
  if (action === 'Open preview') {
    const doc = await vscode.workspace.openTextDocument({ content: previewMd, language: 'markdown' });
    await vscode.window.showTextDocument(doc, vscode.ViewColumn.Beside);
    // Continue to the picker after the preview.
  }

  const picked = await pickRules(result.suggestions);
  if (!picked || picked.length === 0) return;

  const ok = await vscode.window.showWarningMessage(
    `Apply ${picked.length} protection rule${picked.length === 1 ? '' : 's'} to \`${branch}\` on ${repo.owner}/${repo.repo}?`,
    { modal: true, detail: picked.map(p => `\u2022 ${p.label}`).join('\n') + '\n\nThis sends a PUT to the GitHub branch-protection API and requires admin access.' },
    'Apply',
  );
  if (ok !== 'Apply') return;

  const currentlyEnabled = new Set<string>();
  if (result.decision.kind === 'protected') {
    for (const r of result.decision.rules) if (r.enabled) currentlyEnabled.add(r.id);
  }
  const body = buildProtectionPutBody({
    picked: picked.map(p => p.id),
    currentlyEnabled: currentlyEnabled as Set<any>,
    statusCheckContexts: result.signals.workflowJobNames,
  });
  await applyProtection(repo.owner, repo.repo, branch, body);
}

interface RepoSlug { owner: string; repo: string; }

async function ghAvailable(): Promise<boolean> {
  try { await pexec('gh', ['--version'], { timeout: 3000 }); return true; }
  catch { return false; }
}

async function resolveGitHubRepo(git: Git): Promise<RepoSlug | undefined> {
  try {
    const url = (await git.raw(['config', '--get', 'remote.origin.url'])).trim();
    return parseGitHubRepo(url);
  } catch { return undefined; }
}

async function resolveBranch(git: Git, hint?: string): Promise<string | undefined> {
  if (hint) return hint;
  try {
    const out = (await git.raw(['rev-parse', '--abbrev-ref', 'HEAD'])).trim();
    if (!out || out === 'HEAD') return undefined;
    return out;
  } catch { return undefined; }
}

async function loadDefaultBranch(git: Git): Promise<string | undefined> {
  try {
    const out = (await git.raw(['symbolic-ref', '--short', 'refs/remotes/origin/HEAD'])).trim();
    if (out) return out.replace(/^origin\//, '');
  } catch { /* may not be set */ }
  for (const cand of ['main', 'master']) {
    try { await git.raw(['rev-parse', '--verify', cand]); return cand; } catch { /* skip */ }
  }
  return undefined;
}

async function probeBranch(owner: string, repo: string, branch: string): Promise<ProtectionDecision> {
  try {
    const { stdout, stderr } = await pexec('gh', [
      'api', `repos/${owner}/${repo}/branches/${encodeURIComponent(branch)}/protection`,
    ], { timeout: 15000, maxBuffer: 1024 * 1024 });
    return classifyProtection(stdout, stderr ?? '', 0);
  } catch (e: any) {
    return classifyProtection(
      typeof e?.stdout === 'string' ? e.stdout : '',
      typeof e?.stderr === 'string' ? e.stderr : (e?.message ?? ''),
      typeof e?.code === 'number' ? e.code : 1,
    );
  }
}

async function loadEnvironmentSignals(git: Git): Promise<EnvironmentSignals> {
  const repoRoot = (await safeRoot(git)) ?? git.cwd;
  const [workflows, codeownersExists, signedCount] = await Promise.all([
    listWorkflows(repoRoot),
    fileExists(path.join(repoRoot, '.github/CODEOWNERS'))
      .then(found => found || fileExists(path.join(repoRoot, 'CODEOWNERS'))),
    countRecentSignedCommits(git),
  ]);
  return {
    hasCiWorkflows: workflows.length > 0,
    workflowJobNames: workflows,
    hasCodeowners: codeownersExists,
    hasSignedCommits: signedCount.signed > 0,
    recentCommitCount: signedCount.total,
  };
}

async function safeRoot(git: Git): Promise<string | undefined> {
  try { return (await git.raw(['rev-parse', '--show-toplevel'])).trim(); }
  catch { return undefined; }
}

async function fileExists(p: string): Promise<boolean> {
  try { await fs.stat(p); return true; } catch { return false; }
}

async function listWorkflows(repoRoot: string): Promise<string[]> {
  const dir = path.join(repoRoot, '.github/workflows');
  try {
    const ents = await fs.readdir(dir, { withFileTypes: true });
    const names: string[] = [];
    for (const e of ents) {
      if (!e.isFile()) continue;
      if (!/\.(?:ya?ml)$/i.test(e.name)) continue;
      // Use the `name:` field if we can read it cheaply; else fall back to filename.
      try {
        const body = await fs.readFile(path.join(dir, e.name), 'utf8');
        const m = /^\s*name\s*:\s*(.+?)\s*$/m.exec(body);
        names.push(m ? m[1].replace(/^['"]|['"]$/g, '') : e.name.replace(/\.(?:ya?ml)$/i, ''));
      } catch {
        names.push(e.name.replace(/\.(?:ya?ml)$/i, ''));
      }
    }
    return names;
  } catch {
    return [];
  }
}

async function countRecentSignedCommits(git: Git): Promise<{ signed: number; total: number }> {
  try {
    const out = await git.raw(['log', '-30', '--pretty=format:%G?']);
    const codes = out.split('\n').map(s => s.trim()).filter(Boolean);
    const signed = codes.filter(c => c === 'G' || c === 'U' || c === 'X').length;
    return { signed, total: codes.length };
  } catch {
    return { signed: 0, total: 0 };
  }
}

async function pickRules(suggestions: RuleSuggestion[]): Promise<RuleSuggestion[] | undefined> {
  type Pk = vscode.QuickPickItem & { _s: RuleSuggestion };
  const items: Pk[] = suggestions.map(s => ({
    label: `$(${strengthGlyph(s.strength)}) ${s.label}`,
    description: s.strength,
    detail: s.rationale,
    picked: s.strength === 'recommended',
    _s: s,
  }));
  const picked = await vscode.window.showQuickPick(items, {
    canPickMany: true,
    title: 'Pick the rules to apply',
    matchOnDescription: true,
    matchOnDetail: true,
  });
  if (!picked) return undefined;
  return picked.map(p => p._s);
}

function strengthGlyph(s: 'recommended' | 'optional' | 'aggressive'): string {
  switch (s) {
    case 'recommended': return 'verified';
    case 'optional':    return 'star';
    case 'aggressive':  return 'shield';
  }
}

async function applyProtection(owner: string, repo: string, branch: string, body: Record<string, any>): Promise<void> {
  const tmp = path.join(require('os').tmpdir(), `gitsight-protection-${process.pid}-${Date.now()}.json`);
  await fs.writeFile(tmp, JSON.stringify(body), 'utf8');
  try {
    await pexec('gh', [
      'api', '-X', 'PUT',
      `repos/${owner}/${repo}/branches/${encodeURIComponent(branch)}/protection`,
      '--input', tmp,
    ], { timeout: 30000, maxBuffer: 2 * 1024 * 1024 });
    vscode.window.showInformationMessage(`GitSight: applied protection rules to \`${branch}\`.`);
  } catch (e: any) {
    const first = (e?.stderr ?? e?.message ?? String(e)).toString().split('\n')[0];
    vscode.window.showErrorMessage(`GitSight: gh api failed: ${first}`);
  } finally {
    await fs.unlink(tmp).catch(() => {});
  }
}

/**
 * F135 - Delta-only picker for branch protection.
 *
 * When the user re-runs the suggester on a branch that already has
 * rules, show only the CHANGES (would-add / would-strengthen) rather
 * than the full picker. Mirrors the same data-gathering path as
 * `suggestBranchProtection` but routes through the delta classifier.
 *
 * When there are no deltas, surfaces a quick info message rather than
 * an empty picker.
 */
export async function suggestBranchProtectionDelta(repos: RepoManager, branchHint?: string): Promise<void> {
  const git = repos.primary();
  if (!git) {
    vscode.window.showWarningMessage('GitSight: no git repo in workspace.');
    return;
  }
  if (!(await ghAvailable())) {
    vscode.window.showWarningMessage('GitSight: gh CLI not found - cannot probe or set branch protection.');
    return;
  }
  const repo = await resolveGitHubRepo(git);
  if (!repo) {
    vscode.window.showInformationMessage('GitSight: origin is not a GitHub remote.');
    return;
  }
  const branch = await resolveBranch(git, branchHint);
  if (!branch) {
    vscode.window.showInformationMessage('GitSight: no branch selected (detached HEAD?).');
    return;
  }

  const result = await vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: `GitSight: computing protection delta for \`${branch}\`\u2026`,
    },
    async () => {
      const [decision, defaultBranch, signals] = await Promise.all([
        probeBranch(repo.owner, repo.repo, branch),
        loadDefaultBranch(git),
        loadEnvironmentSignals(git),
      ]);
      const role = classifyBranchRole({ branch, defaultBranch });
      const suggestions = suggestProtectionRules({ branch, role, current: decision, signals });
      const deltas = computeProtectionDelta({ current: decision, proposed: suggestions });
      return { decision, defaultBranch, signals, role, suggestions, deltas };
    },
  );

  const verdict = classifyDeltaVerdict(result.deltas);
  if (verdict === 'no-delta') {
    const choice = await vscode.window.showInformationMessage(
      `GitSight: \`${branch}\` (${result.role}) is already at the proposed baseline.`,
      'Open full picker', 'Open report',
    );
    if (choice === 'Open full picker') {
      await suggestBranchProtection(repos, branch);
    } else if (choice === 'Open report') {
      await openDeltaReport(branch, result.deltas);
    }
    return;
  }

  // Build the delta picker.
  const visibleDeltas = selectDeltaRows(result.deltas);
  const picked = await pickDeltas(branch, visibleDeltas, result.deltas);
  if (!picked || picked.length === 0) return;

  const ok = await vscode.window.showWarningMessage(
    `Apply ${picked.length} change${picked.length === 1 ? '' : 's'} to \`${branch}\` on ${repo.owner}/${repo.repo}?`,
    {
      modal: true,
      detail: picked.map(p => `\u2022 ${labelForDelta(p)}`).join('\n')
        + '\n\nThis sends a PUT to the GitHub branch-protection API. Existing enabled rules are preserved.',
    },
    'Apply',
  );
  if (ok !== 'Apply') return;

  const currentlyEnabled = new Set<string>();
  if (result.decision.kind === 'protected') {
    for (const r of result.decision.rules) if (r.enabled) currentlyEnabled.add(r.id);
  }
  const body = buildProtectionPutBody({
    picked: picked.map(p => p.id),
    currentlyEnabled: currentlyEnabled as Set<any>,
    statusCheckContexts: result.signals.workflowJobNames,
  });
  await applyProtection(repo.owner, repo.repo, branch, body);
}

function labelForDelta(d: ProtectionRuleDelta): string {
  const kind = d.change === 'would-add' ? 'add' : 'enable';
  return `${d.label} (${kind})`;
}

async function pickDeltas(
  branch: string,
  visible: ProtectionRuleDelta[],
  all: ProtectionRuleDelta[],
): Promise<ProtectionRuleDelta[] | undefined> {
  type Pk = vscode.QuickPickItem & { _d?: ProtectionRuleDelta; _allChanges?: true; _report?: true };
  const items: Pk[] = [];
  if (visible.length > 1) {
    items.push({
      label: '$(check-all) Apply all changes',
      description: `${visible.length} pending`,
      _allChanges: true,
    });
    items.push({ label: '', kind: vscode.QuickPickItemKind.Separator } as any);
  }
  for (const d of visible) {
    const glyph = d.change === 'would-add' ? 'add' : 'plus';
    items.push({
      label: `$(${glyph}) ${d.label}`,
      description: d.change === 'would-add' ? 'add' : 'strengthen',
      detail: describeDeltaRow(d),
      picked: d.strength === 'recommended',
      _d: d,
    });
  }
  items.push({ label: '', kind: vscode.QuickPickItemKind.Separator } as any);
  items.push({ label: '$(file) Open full delta report', _report: true });

  const picked = await vscode.window.showQuickPick(items, {
    canPickMany: true,
    title: describeDeltaTitle(branch, all),
    matchOnDescription: true,
    matchOnDetail: true,
  });
  if (!picked) return undefined;
  if (picked.some(p => p._report)) {
    await openDeltaReport(branch, all);
    return undefined;
  }
  if (picked.some(p => p._allChanges)) {
    const allIds = new Set(pickAllChanges(all));
    return all.filter(d => allIds.has(d.id));
  }
  return picked.map(p => p._d!).filter(Boolean);
}

async function openDeltaReport(branch: string, deltas: ProtectionRuleDelta[]): Promise<void> {
  const md = buildDeltaReport({ branch, deltas });
  const doc = await vscode.workspace.openTextDocument({ content: md, language: 'markdown' });
  await vscode.window.showTextDocument(doc, vscode.ViewColumn.Beside);
}
